site_name: mkdghp
site_url: https://s03d4-164.github.io/mkdghp/
theme:
  name: material
  language: ja
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - navigation.sections
  font: false
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.magiclink
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - md_in_html
plugins:
  - search:
  - macros:
  - i18n:
      docs_structure: folder
      languages:
        - locale: ja
          default: true
          name: Japanese
          build: true
  - blogging:
      dirs:
        - .
      locale: ja_JP
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/S03D4-164/
nav:
