on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-static-i18n
      - run: mkdocs gh-deploy --force
